### ISSUE TITLE
/grant command issue

### ISSUE THREAD

**Issue by ignRxflect** [AndyReckt/Holiday#5]
[11:20:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'grant Siqk' in me.andyreckt.holiday.bukkit.util.sunset.executor.SunsetCommand(grant)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[server.jar:git-mSpigot-unknown]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:808) ~[server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1293) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1134) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:31) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:74) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:291) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:94) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:688) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:285) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:612) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:513) [server.jar:git-mSpigot-unknown]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-mSpigot-unknown]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
        at me.andyreckt.holiday.bukkit.util.sunset.executor.SunsetCommand.execute(SunsetCommand.java:162) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[server.jar:git-mSpigot-unknown]
        ... 12 more
Caused by: java.lang.NoClassDefFoundError: com/mojang/authlib/GameProfile
        at me.andyreckt.holiday.bukkit.util.item.ItemBuilder.texture(ItemBuilder.java:374) ~[?:?]
        at me.andyreckt.holiday.bukkit.util.menu.pagination.PageButton.getButtonItem(PageButton.java:28) ~[?:?]
        at me.andyreckt.holiday.bukkit.util.menu.Menu.createItemStack(Menu.java:89) ~[?:?]
        at me.andyreckt.holiday.bukkit.util.menu.Menu.openMenu(Menu.java:138) ~[?:?]
        at me.andyreckt.holiday.bukkit.commands.GrantCommands.grant(GrantCommands.java:28) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
        at me.andyreckt.holiday.bukkit.util.sunset.executor.SunsetCommand.execute(SunsetCommand.java:162) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[server.jar:git-mSpigot-unknown]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: com.mojang.authlib.GameProfile
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_51]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-mSpigot-unknown]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-mSpigot-unknown]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
        at me.andyreckt.holiday.bukkit.util.item.ItemBuilder.texture(ItemBuilder.java:374) ~[?:?]
        at me.andyreckt.holiday.bukkit.util.menu.pagination.PageButton.getButtonItem(PageButton.java:28) ~[?:?]
        at me.andyreckt.holiday.bukkit.util.menu.Menu.createItemStack(Menu.java:89) ~[?:?]
        at me.andyreckt.holiday.bukkit.util.menu.Menu.openMenu(Menu.java:138) ~[?:?]
        at me.andyreckt.holiday.bukkit.commands.GrantCommands.grant(GrantCommands.java:28) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
        at me.andyreckt.holiday.bukkit.util.sunset.executor.SunsetCommand.execute(SunsetCommand.java:162) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[server.jar:git-mSpigot-unknown]
        ... 12 more

**Comment by PROSTONGO** [comment]
use paper spigot

**Comment by PROSTONGO** [comment]
1.8.8 recommended

**Comment by ignRxflect** [comment]
Alright will try that

**Comment by AndyReckt** [comment]
> Caused by: java.lang.ClassNotFoundException: com.mojang.authlib.GameProfile
Ok i did not think this through, the GameProfile class is not in the same package in 1.7 and 1.8, i will fix this ASAP

**Comment by AndyReckt** [comment]
@ignRxflect I have fixed it! (https://github.com/AndyReckt/Holiday/commit/11d55b109e858e6cd50f6df198278b8318227edc) It may spam your console with some null errors i cannot help it
