### ISSUE TITLE
Mongo

### ISSUE THREAD

**Issue by ignRxflect** [AndyReckt/Holiday#7]
25.01 01:19:04 [Server] [WARN] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
25.01 01:19:04 [Server] [WARN] SLF4J: Defaulting to no-operation (NOP) logger implementation
25.01 01:19:04 [Server] [WARN] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
25.01 01:19:35 [Server] [INFO] [Holiday] [[ERROR]] An error occurred while enabling the plugin. Showing stacktrace:
25.01 01:19:35 [Server] [WARN] me.andyreckt.holiday.relocations.com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=rs0:27017, type=UNKNOWN, state=CONNECTING, exception={me.andyreckt.holiday.relocations.com.mongodb.MongoSocketException: rs0}, caused by {java.net.UnknownHostException: rs0}}]
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:155)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:105)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:287)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.core.user.rank.RankManager.loadRanks(RankManager.java:34)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.core.user.rank.RankManager.<init>(RankManager.java:26)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.core.HolidayAPI.<init>(HolidayAPI.java:68)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.api.API.create(API.java:12)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.bukkit.Holiday.setupApi(Holiday.java:122)
25.01 01:19:35 [Server] [WARN] at me.andyreckt.holiday.bukkit.Holiday.onEnable(Holiday.java:93)
25.01 01:19:35 [Server] [WARN] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
25.01 01:19:35 [Server] [WARN] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
25.01 01:19:35 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
25.01 01:19:35 [Server] [WARN] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:369)
25.01 01:19:35 [Server] [WARN] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:328)
25.01 01:19:35 [Server] [WARN] at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:381)
25.01 01:19:35 [Server] [WARN] at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:345)
25.01 01:19:35 [Server] [WARN] at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:305)
25.01 01:19:35 [Server] [WARN] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:239)
25.01 01:19:35 [Server] [WARN] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:526)
25.01 01:19:35 [Server] [WARN] at java.lang.Thread.run(Thread.java:748)
25.01 01:19:35 [Server] [INFO] [Holiday] [[ERROR]] Stopping the server...

When I use clevercloud to use holiday it's buggin ive tried 2 spigots and 3 different mongos and none is working. Also when i log in to mongocompass it works fine.

**Comment by ignRxflect** [comment]
[19:41:26 INFO]: [Holiday] FOUND FULLY COMPATIBLE SPIGOT VERSION, LOADING PLUGIN
[19:41:27 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:41:27 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:41:27 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[19:41:30 INFO]: [Holiday] [ERROR] An error occurred while enabling the plugin. Showing stacktrace:
[19:41:30 WARN]: me.andyreckt.holiday.relocations.com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on holiday to execute command { find: "ranks", $db: "holiday", $clusterTime: { clusterTime: Timestamp(1674693570, 21), signature: { hash: BinData(0, F039E85065014702B09BA7412406AFE0D8A92AC3), keyId: 7146300907339120641 } }, lsid: { id: UUID("35416d4b-f505-4f7e-8410-f25a570636ea") } }' on server n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.operation.FindOperation$1.call(FindOperation.java:735)
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.operation.FindOperation$1.call(FindOperation.java:725)
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.operation.FindOperation.execute(FindOperation.java:725)
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.operation.FindOperation.execute(FindOperation.java:89)
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:199)
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143)
[19:41:30 WARN]:        at me.andyreckt.holiday.relocations.com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
[19:41:30 WARN]:        at me.andyreckt.holiday.core.user.rank.RankManager.loadRanks(RankManager.java:34)
[19:41:30 WARN]:        at me.andyreckt.holiday.core.user.rank.RankManager.<init>(RankManager.java:26)
[19:41:30 WARN]:        at me.andyreckt.holiday.core.HolidayAPI.<init>(HolidayAPI.java:69)
[19:41:30 WARN]:        at me.andyreckt.holiday.api.API.create(API.java:12)
[19:41:30 WARN]:        at me.andyreckt.holiday.bukkit.Holiday.setupApi(Holiday.java:121)
[19:41:30 WARN]:        at me.andyreckt.holiday.bukkit.Holiday.onEnable(Holiday.java:92)
[19:41:30 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[19:41:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[19:41:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[19:41:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:369)
[19:41:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:328)
[19:41:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:381)
[19:41:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:345)
[19:41:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:305)
[19:41:30 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:239)
[19:41:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:526)
[19:41:30 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:41:30 INFO]: [Holiday] [ERROR] Stopping the server...

**Comment by AndyReckt** [comment]
Hello, you need to use mongo URI, but still set the database name as the name of the database you want to be using, i am planning to change that later, but for now that is how you should do it
@ignRxflect

**Comment by ignRxflect** [comment]
Alright thank you!

**Comment by ignRxflect** [comment]
[16:10:41 INFO]: [Holiday] [ERROR] An error occurred while enabling the plugin. Showing stacktrace:
[16:10:41 WARN]: java.lang.NullPointerException
[16:10:41 WARN]:        at me.andyreckt.holiday.core.server.Server.setWhitelistRank(Server.java:61)
[16:10:41 WARN]:        at me.andyreckt.holiday.bukkit.Holiday.setupServer(Holiday.java:131)
[16:10:41 WARN]:        at me.andyreckt.holiday.bukkit.Holiday.onEnable(Holiday.java:93)
[16:10:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[16:10:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[16:10:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[16:10:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:369)
[16:10:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:328)
[16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:381)
[16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:345)
[16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:305)
[16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:239)
[16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:526)
[16:10:41 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:10:41 INFO]: [Holiday] [ERROR] Stopping the server...
[16:10:41 INFO]: Done (6.511s)! For help, type "help" or "?"
[16:10:41 INFO]: Stopping server
[16:10:41 INFO]: [Holiday] Disabling Holiday v1.1.2
[16:10:41 ERROR]: Error occurred while disabling Holiday v1.1.2 (Is it up to date?)
java.lang.NullPointerException: null
        at me.andyreckt.holiday.bukkit.Holiday.onDisable(Holiday.java:263) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:348) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:423) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:619) [server.jar:1.8.8-R0.1-SNAPSHOT]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
[16:10:41 INFO]: [WorldEdit] Disabling WorldEdit v6.1.7;dd00bb1
[16:10:41 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.2
[16:10:41 INFO]: [Vault] Disabling Vault v1.5.5-b47
[16:10:41 INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v21.03.09-a5e5590-1285-22.3.8
[16:10:41 INFO]: [LunarClient-API] Disabling LunarClient-API v${git.commit.id.abbrev}
[16:10:41 INFO]: Saving players
[16:10:41 INFO]: Saving worlds
[16:10:41 INFO]: Saving chunks for level 'world'/Overworld
[16:10:41 INFO]: Saving chunks for level 'world_nether'/Nether
[16:10:41 INFO]: Saving chunks for level 'world_the_end'/The End

Still getting this error

**Comment by AndyReckt** [comment]
> [16:10:41 INFO]: [Holiday] [ERROR] An error occurred while enabling the plugin. Showing stacktrace:
> 
> [16:10:41 WARN]: java.lang.NullPointerException
> 
> [16:10:41 WARN]:        at me.andyreckt.holiday.core.server.Server.setWhitelistRank(Server.java:61)
> 
> [16:10:41 WARN]:        at me.andyreckt.holiday.bukkit.Holiday.setupServer(Holiday.java:131)
> 
> [16:10:41 WARN]:        at me.andyreckt.holiday.bukkit.Holiday.onEnable(Holiday.java:93)
> 
> [16:10:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
> 
> [16:10:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
> 
> [16:10:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
> 
> [16:10:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:369)
> 
> [16:10:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:328)
> 
> [16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:381)
> 
> [16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:345)
> 
> [16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:305)
> 
> [16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:239)
> 
> [16:10:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:526)
> 
> [16:10:41 WARN]:        at java.lang.Thread.run(Unknown Source)
> 
> [16:10:41 INFO]: [Holiday] [ERROR] Stopping the server...
> 
> [16:10:41 INFO]: Done (6.511s)! For help, type "help" or "?"
> 
> [16:10:41 INFO]: Stopping server
> 
> [16:10:41 INFO]: [Holiday] Disabling Holiday v1.1.2
> 
> [16:10:41 ERROR]: Error occurred while disabling Holiday v1.1.2 (Is it up to date?)
> 
> java.lang.NullPointerException: null
> 
>         at me.andyreckt.holiday.bukkit.Holiday.onDisable(Holiday.java:263) ~[?:?]
> 
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[server.jar:1.8.8-R0.1-SNAPSHOT]
> 
>         at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [server.jar:1.8.8-R0.1-SNAPSHOT]
> 
>         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427) [server.jar:1.8.8-R0.1-SNAPSHOT]
> 
>         at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:420) [server.jar:1.8.8-R0.1-SNAPSHOT]
> 
>         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:348) [server.jar:1.8.8-R0.1-SNAPSHOT]
> 
>         at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:423) [server.jar:1.8.8-R0.1-SNAPSHOT]
> 
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:619) [server.jar:1.8.8-R0.1-SNAPSHOT]
> 
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
> 
> [16:10:41 INFO]: [WorldEdit] Disabling WorldEdit v6.1.7;dd00bb1
> 
> [16:10:41 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.2
> 
> [16:10:41 INFO]: [Vault] Disabling Vault v1.5.5-b47
> 
> [16:10:41 INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v21.03.09-a5e5590-1285-22.3.8
> 
> [16:10:41 INFO]: [LunarClient-API] Disabling LunarClient-API v${git.commit.id.abbrev}
> 
> [16:10:41 INFO]: Saving players
> 
> [16:10:41 INFO]: Saving worlds
> 
> [16:10:41 INFO]: Saving chunks for level 'world'/Overworld
> 
> [16:10:41 INFO]: Saving chunks for level 'world_nether'/Nether
> 
> [16:10:41 INFO]: Saving chunks for level 'world_the_end'/The End
> 
> 
> 
> Still getting this error


You need to reset your mongo & redis

**Comment by ignRxflect** [comment]
Should I make new ones or?

**Comment by ignRxflect** [comment]
Also if you want to add me on discord rxflect#1437 if that easier for you

**Comment by AndyReckt** [comment]
you need to stop redis and delete your redis.rdb, and you need to change the mongo database OR drop the current one

**Comment by ignRxflect** [comment]
Alright

**Comment by AndyReckt** [comment]
Resolved in dms
